-- 서울에 위치한 식당 목록 출력하기
SELECT REST_INFO.REST_ID,REST_INFO.REST_NAME,REST_INFO.FOOD_TYPE,REST_INFO.FAVORITES,REST_INFO.ADDRESS,ROUND(AVG(REST_REVIEW.REVIEW_SCORE),2) as SCORE
FROM REST_INFO
INNER JOIN REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_ID HAVING ADDRESS LIKE '서울%'
ORDER BY ROUND(AVG(REST_REVIEW.REVIEW_SCORE),2) DESC,REST_INFO.FAVORITES DESC;