-- 조건에 부합하는 중고거래 댓글 조회하기
SELECT  USED_GOODS_BOARD.TITLE,
        USED_GOODS_BOARD.BOARD_ID,
        USED_GOODS_REPLY.REPLY_ID,
        USED_GOODS_REPLY.WRITER_ID,
        USED_GOODS_REPLY.CONTENTS,
        DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
  FROM  USED_GOODS_BOARD
 INNER
  JOIN  USED_GOODS_REPLY
    ON  USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
 WHERE  SUBSTR(USED_GOODS_REPLY.CREATED_DATE,1,7) = '2022-10'
 ORDER
    BY  USED_GOODS_REPLY.CREATED_DATE ASC,USED_GOODS_BOARD.TITLE ASC;